### ISSUE TITLE
Are there any plans to release the BabelCoder model on Hugging Face?

### ISSUE THREAD

**Issue by brick-pid** [google-research/babelcode#10]
Thank you for your work. We are very interested in the Babel models you trained (1B, 2B, and 4B). Do you plan to release these models on Hugging Face?

**Comment by gabeorlanski** [comment]
Thanks! Unfortunately the model itself will not be released but the evaluation datasets are on HuggingFace:

https://huggingface.co/datasets/gabeorlanski/bc-humaneval
https://huggingface.co/datasets/gabeorlanski/bc-transcoder
https://huggingface.co/datasets/gabeorlanski/bc-mbpp
https://huggingface.co/datasets/gabeorlanski/tp3
